UPDATE dmd_product
SET FP10_MDA = 1
WHERE DMDID IN (
  SELECT DMDID
  FROM dmd_product
  INNER join AMP
    ON AMP.VPID = DMDID
    OR AMP.APID = DMDID
  INNER JOIN AMPP
    ON AMP.APID = AMPP.APID
  INNER JOIN PRESCRIB_INFO
    ON PRESCRIB_INFO.APPID = AMPP.APPID
  WHERE PRESCRIB_INFO.FP10_MDA = 1)
