INSERT OR REPLACE INTO dmd_product
SELECT
  AMP.APID AS DMDID,
  NULL AS BNF_CODE,
  AMP.VPID,
  AMP.DESC AS DISPLAY_NAME,
  EMA,
  1 AS PRES_STATCD,
  AVAIL_RESTRICTCD,
  2 AS product_type,
  0 AS NON_AVAILCD,
  2 AS concept_class,
  0 AS NURSE_F,
  0 AS DENT_F,
  PROD_ORDER_NO,
  0 AS SCHED_1,
  0 AS PADM,
  0 AS SCHED_2,
  0 AS FP10_MDA,
  0 AS ACBS,
  0 AS assort_flav,
  0 AS CATCD,
  NULL AS tariff_category
FROM
  AMP
INNER JOIN
  VMP
ON
  VMP.VPID = AMP.VPID
LEFT JOIN
  AP_INFO
ON
  AP_INFO.APID = AMP.APID
WHERE
  AMP.INVALID IS NULL
  AND (AMP.COMBPRODCD IS NULL
    OR AMP.COMBPRODCD = 1)
  AND (PARALLEL_IMPORT IS NULL
    OR PARALLEL_IMPORT = 0) UNION ALL
SELECT
  VPID AS DMDID,
  NULL AS BNF_CODE,
  VPID,
  NM AS DISPLAY_NAME,
  0 AS EMA,
  PRES_STATCD,
  NULL AS AVAIL_RESTRICTCD,
  1 AS product_type,
  NON_AVAILCD,
  1 AS concept_class,
  0 AS NURSE_F,
  0 AS DENT_F,
  NULL AS PROD_ORDER_NO,
  0 AS SCHED_1,
  0 AS PADM,
  0 AS SCHED_2,
  0 AS FP10_MDA,
  0 AS ACBS,
  0 AS assort_flav,
  0 AS CATCD,
  NULL AS tariff_category
FROM
  VMP
WHERE
  INVALID IS NULL
  AND (COMBPRODCD IS NULL
    OR COMBPRODCD = 1)
