UPDATE dmd_product
SET DENT_F = 1
WHERE DMDID IN (SELECT
  DMDID
FROM dmd_product
INNER JOIN AMP
  ON AMP.APID = DMDID
  OR AMP.VPID = DMDID
INNER JOIN AMPP
  ON AMPP.APID = AMP.APID
INNER JOIN PRESCRIB_INFO
  ON AMPP.APPID = PRESCRIB_INFO.APPID
WHERE PRESCRIB_INFO.DENT_F = 1)
