UPDATE dmd_product
SET SCHED_1 = 1
WHERE DMDID IN (SELECT
  dmd_product.DMDID
FROM dmd_product
INNER JOIN AMP
  ON AMP.APID = dmd_product.DMDID
INNER JOIN AMPP
  ON AMPP.APID = AMP.APID
INNER JOIN PRESCRIB_INFO
  ON AMPP.APPID = PRESCRIB_INFO.APPID
  AND PRESCRIB_INFO.SCHED_1 = 1
LEFT OUTER JOIN (SELECT
  DMDID
FROM dmd_product
INNER JOIN AMP
  ON AMP.APID = dmd_product.DMDID
INNER JOIN AMPP
  ON AMPP.APID = AMP.APID
INNER JOIN PRESCRIB_INFO
  ON AMPP.APPID = PRESCRIB_INFO.APPID
  AND PRESCRIB_INFO.SCHED_1 != 1) notschedule_1
  ON dmd_product.DMDID = notschedule_1.DMDID
WHERE notschedule_1.DMDID IS NULL)
