UPDATE dmd_product
SET assort_flav = 1
WHERE DMDID IN (
  SELECT DMDID
  FROM dmd_product
  INNER JOIN AMP
    ON dmd_product.DMDID = AMP.APID
  WHERE AMP.SUPPCD = 21014611000001102
  AND AMP.AVAIL_RESTRICTCD != 9
  AND ACBS = 1)
